import React from "react";
import ProjectCard1 from "./ProjectCard1";
import ProjectCard2 from "./ProjectCard2";
import ProjectCard3 from "./ProjectCard3";

const Projects = () => {
  return (
    <div id="Projects" className="p-10 md:p-24 text-white ">
      <h1 className="text-2xl md:text-4xl text-white font-bold">Projects</h1>
      <div className="py-12 px-8 flex flex-wrap gap-5">
        <ProjectCard1
          title="Bookie – A Book Selling Platform!"
          main="A while ago, I started building a digital library where librarians could track borrowed books, and students could check their issued books and due dates. Now, I’ve taken this idea further and transformed it into Bookie – a platform where book sellers can list their books, manage stock, and set prices, while users can explore, buy books via UPI, wallets, credit/debit cards, and even contact sellers directly via email!"
        />
        <ProjectCard2
          title="Bus Management System"
          main="I have recently been working on a new JDBC (Java Database Connectivity) project. In this project, I utilized MySQL as the database and Core Java as the backend language. I implemented Object-Oriented Programming (OOPs) concepts such as Encapsulation (Data Hiding) to secure my data and Exception Handling to manage risky code. I used JDBC to connect Core Java with MySQL."
        />
        <ProjectCard3
          title="OTP Verification System"
          main="I created an application that generates and verifies OTPs (One-Time Passwords). The system sends an OTP to the provided email address, and then verifies the email by comparing the OTP sent to the email with the one generated by the system.I don't use the front end because this is primarily a testing project, which is part of my main project (library). In this part, users verify their email addresses, and they can log in and change their passwords using their email ID. That’s why I make the requests using Postman."
        />
      </div>
    </div>
  );
};

export default Projects;
